{{- if eq .Values.nacos.storage.type "mysql"}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
data: 
  {{- with .Values.nacos.storage.db }}
  mysql.db.host: {{.host | quote }}
  mysql.db.name: {{ .name | quote }}
  mysql.port: {{ .port | default 3306 | quote }}
  mysql.user: {{ .username | quote }}
  mysql.password: {{ .password | quote }}
  mysql.param: {{ .param | default "characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false" | quote }}
  {{- end }}
  {{- end }}



