{{- /*
Copyright VMware, Inc.
SPDX-License-Identifier: APACHE-2.0
*/}}

apiVersion: v1
kind: ConfigMap
metadata:
  name: lizardcd
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}

data: 
  {{- if (include "lizardcd.ui.enabled" .) }}
  nginx.conf: |
    user  nginx;
    worker_processes  auto;
    error_log  /var/log/nginx/error.log warn;
    pid        /tmp/nginx.pid;
    events {
      worker_connections  8192;
    }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for" '
                        '"$upstream_addr" $request_time $upstream_response_time';
      access_log  /var/log/nginx/access.log  main;
      sendfile        on;
      keepalive_timeout  65;
      client_max_body_size 100m;
      server {
        listen       80;
        server_name  localhost;
        
        location / {
          root   /usr/share/nginx/html;
          index  index.html;
          try_files $uri $uri/ /index.html;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
          root   /usr/share/nginx/html;
        }

        # Todo: To be removed after frondend adjusted to real service labels.
        location /consul {
          # proxy_http_version 1.1;
          proxy_set_header Host $proxy_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          {{- if .Values.ui.externalServer }}
          proxy_pass http://{{ include "lizardcd.ui.externalServer" .}};
          {{- else }}
          proxy_pass http://{{ include "lizardcd.server.fullname" . }}:5117;
          {{- end }}
        }
        location /lizardcd {
          # proxy_http_version 1.1;
          proxy_set_header Host $proxy_host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          {{- if .Values.ui.externalServer }}
          proxy_pass http://{{ include "lizardcd.ui.externalServer" .}};
          {{- else }}
          proxy_pass http://{{ include "lizardcd.server.fullname" . }}:5117;
          {{- end }}
        }
      }
    }
  {{- end }}
  {{- if and (include "lizardcd.server.enabled" .) .Values.server.configuration }}
  lizardcd-server.yaml: |
    {{- include "common.tplvalues.render" ( dict "value" .Values.server.configuration "context" $ ) | nindent 4 }}
  {{- end }}
  {{- if and (include "lizardcd.agent.enabled" .) .Values.agent.configuration }}
  lizardcd-agent.yaml: |
    {{- include "common.tplvalues.render" ( dict "value" .Values.agent.configuration "context" $ ) | nindent 4 }}
  {{- end }}


