{{- if and (include "lizardcd.agent.enabled" .) .Values.agent.serviceAccount.create -}}
{{- $fullName := include "lizardcd.agent.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "lizardcd.agent.serviceAccountName" . }}"
  {{- if .Values.agent.serviceAccount.annotations -}}
  annotations:
    {{- include "common.tplvalues.render" (dict "values" .Values.agent.serviceAccount.annotations "context" $) | nindent 4 -}}
  labels:
    {{- include "lizardcd.labels" . | nindent 4 }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: {{ $fullName | quote }}
  {{- end }}
secrets:
  - name: lizardcd-token
{{- end -}}


